---
apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: playbook2image
  annotations:
    description: >
      Source-to-Image (S2I) builder image for packaging Ansible playbooks
      as a self-executing container
    tags: "ansible,s2i,builder"
  labels:
    template: playbook2image
objects:
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: ${NAME}
      annotations:
        description: >
          Source-to-Image (S2I) builder image for packaging Ansible playbooks
          as a self-executing container
        tags: "builder,ansible,ansible-playbook,s2i"
        iconClass: "icon-ansible"
      labels:
        template: playbook2image
        name: ${NAME}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${TAG}
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        git:
          uri: ${PLAYBOOK_REPOSITORY_URL}
        type: Git
      strategy:
        sourceStrategy:
          from:
            kind: DockerImage
            name: ${BUILD_IMAGE}
        type: Source
      triggers:
        - github:
            secret: ${GITHUB_WEBHOOK_SECRET}
          type: GitHub
        - generic:
            secret: ${GENERIC_WEBHOOK_SECRET}
          type: Generic
        - type: ConfigChange
    status:
      lastVersion: 0
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
    spec: {}
parameters:
  - name: PLAYBOOK_REPOSITORY_URL
    description: The URL of the playbook repository
    required: true
  - name: NAME
    description: Name of the new image
    required: true
  - name: TAG
    description: Tag for the new image, e.g. latest
    value: latest
  - name: BUILD_IMAGE
    description: Base build image
    value: docker.io/aweiteka/playbook2image:latest
  - name: GITHUB_WEBHOOK_SECRET
    description: A secret string used to configure the GitHub webhook
    generate: expression
    from: "[a-zA-Z0-9]{40}"
    message: "... The GitHub webhook secret is ${GITHUB_WEBHOOK_SECRET} ..."
  - name: GENERIC_WEBHOOK_SECRET
    description: A secret string used to configure the generic webhook
    generate: expression
    from: "[a-zA-Z0-9]{40}"
    message: "... The generic webhook secret is ${GENERIC_WEBHOOK_SECRET} ..."
