apiVersion: batch/v1
kind: Job
metadata:
  name: testplaybook
spec:
  parallelism: 1    
  completions: 1    
  template:         
    metadata:
      name: testplaybook
      labels:
        app: testplaybook
    spec:
      containers:
      - name: testplaybook
        image: 172.30.114.236:5000/some_project/atomic-host-tests
        env:
        - name: PLAYBOOK_FILE
          value: tests/new-image-smoketest/main.yaml
        - name: ANSIBLE_HOST_KEY_CHECKING
          value: "False"
        - name: OPTS
          value: "-vvv --private-key /opt/app-root/src/.ssh/id_rsa"
        volumeMounts:
        - name: sshkey
          mountPath: /opt/app-root/src/.ssh/id_rsa
      volumes:
        - name: sshkey
          secret:
            secretName: sshkey
      restartPolicy: Never


