# An example ScheduledJob to run a regular check of OpenShift's internal
# certificate status.
# The referenced image is a containerized openshift-ansible build
# (see build-openshift-ansible.yaml for an example how to build it and
# update the 'image' reference to the ImageStream's dockerPullSpec)
# It also expects ssh keys to be present in a Secret named 'sshkey'
---
apiVersion: batch/v2alpha1  # ScheduledJob are alpha in 1.3 and are
kind: ScheduledJob          # renamed to CronJob in k8s 1.5
metadata:
  name: certificate-check
  labels:
    app: certcheck
spec:
  schedule: "0 1 * * *"  # Run every day at 01:00
  jobTemplate:
    spec:
      template:
        metadata:
          name: certificate-check
          labels:
            app: certcheck
        spec:
          containers:
          - name: openshift-ansible
            # imagestream or internal/external registry
            image: 172.30.114.236:5000/my_oa_build/openshift-ansible
            env:
            - name: PLAYBOOK_FILE
              value: playbooks/certificate_expiry/default.yaml
            - name: INVENTORY_URL
              # inventory is served by an external HTTP server
              value: http://example.com/myhosts
            - name: ANSIBLE_PRIVATE_KEY_FILE
              value: /opt/app-root/src/.ssh/id_rsa/ssh-privatekey
            - name: ANSIBLE_HOST_KEY_CHECKING
              value: "False"
            - name: OPTS
              value: "-v"
            volumeMounts:
            - name: sshkey
              mountPath: /opt/app-root/src/.ssh/id_rsa
          volumes:
          - name: sshkey
            secret:
              secretName: sshkey
          restartPolicy: Never
